### ISSUE TITLE
practica 2 

### ISSUE THREAD

**Issue by yaritzaov123** [SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-julio-cesar-gonzalez-lopez#2]
[PACTICA 2.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-equipo-julio-cesar-gonzalez-lopez/files/7531356/PACTICA.2.pdf)

**Comment by saul19bautista** [comment]
calificación 27 % buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
